//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.WebFresher042023.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReceiptVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReceiptVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.WebFresher042023.Core.Resources.ReceiptVN", typeof(ReceiptVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hạch toán phải lớn hơn hoặc bằng ngày chứng từ. Vui lòng kiểm tra lại..
        /// </summary>
        public static string ErrorLogic_Date_AccountingDate {
            get {
                return ResourceManager.GetString("ErrorLogic_Date_AccountingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không tồn tại trong hệ thống..
        /// </summary>
        public static string ErrorLogic_Exist_EmployeeId {
            get {
                return ResourceManager.GetString("ErrorLogic_Exist_EmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhà cung cấp không tồn tại trong hệ thống..
        /// </summary>
        public static string ErrorLogic_Exist_ProviderId {
            get {
                return ResourceManager.GetString("ErrorLogic_Exist_ProviderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số phiếu đã tồn tại trong hệ thống..
        /// </summary>
        public static string ErrorLogic_Exist_ReceiptNumber {
            get {
                return ResourceManager.GetString("ErrorLogic_Exist_ReceiptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu đã được ghi sổ, không được xóa.
        /// </summary>
        public static string ErrorLogic_IsNoted {
            get {
                return ResourceManager.GetString("ErrorLogic_IsNoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản có&lt;{0}&gt; chi tiết theo nhà cung cấp, chứng từ hạch toán thiếu &lt;Nhà cung cấp&gt;..
        /// </summary>
        public static string ErrorLogic_LackOfProvider_AccountBalance {
            get {
                return ResourceManager.GetString("ErrorLogic_LackOfProvider_AccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản nợ &lt;{0}&gt; chi tiết theo nhà cung cấp, chứng từ hạch toán thiếu &lt;Nhà cung cấp&gt;..
        /// </summary>
        public static string ErrorLogic_LackOfProvider_AccountDebt {
            get {
                return ResourceManager.GetString("ErrorLogic_LackOfProvider_AccountDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản có&lt;{0}&gt; không theo nhà cung cấp..
        /// </summary>
        public static string ErrorLogic_NotFollowProvider_AccountBalance {
            get {
                return ResourceManager.GetString("ErrorLogic_NotFollowProvider_AccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản nợ &lt;{0}&gt; không theo nhà cung cấp..
        /// </summary>
        public static string ErrorLogic_NotFollowProvider_AccountDebt {
            get {
                return ResourceManager.GetString("ErrorLogic_NotFollowProvider_AccountDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu_Chi_Tien_Mat.xlsx.
        /// </summary>
        public static string Export_FileName {
            get {
                return ResourceManager.GetString("Export_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hạch toán.
        /// </summary>
        public static string Export_Title_AccountingDate {
            get {
                return ResourceManager.GetString("Export_Title_AccountingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Export_Title_Address {
            get {
                return ResourceManager.GetString("Export_Title_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tượng.
        /// </summary>
        public static string Export_Title_Obj {
            get {
                return ResourceManager.GetString("Export_Title_Obj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đối tượng.
        /// </summary>
        public static string Export_Title_ObjCode {
            get {
                return ResourceManager.GetString("Export_Title_ObjCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diễn giải.
        /// </summary>
        public static string Export_Title_Reason {
            get {
                return ResourceManager.GetString("Export_Title_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THU CHI TIỀN MẶT.
        /// </summary>
        public static string Export_Title_Receipt {
            get {
                return ResourceManager.GetString("Export_Title_Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày chứng từ.
        /// </summary>
        public static string Export_Title_ReceiptDate {
            get {
                return ResourceManager.GetString("Export_Title_ReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chứng từ.
        /// </summary>
        public static string Export_Title_ReceiptNumber {
            get {
                return ResourceManager.GetString("Export_Title_ReceiptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền.
        /// </summary>
        public static string Export_Title_TotalMoney {
            get {
                return ResourceManager.GetString("Export_Title_TotalMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại chứng từ.
        /// </summary>
        public static string Export_Title_TypeReceipt {
            get {
                return ResourceManager.GetString("Export_Title_TypeReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu chi.
        /// </summary>
        public static string Text_Payment {
            get {
                return ResourceManager.GetString("Text_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu thu.
        /// </summary>
        public static string Text_Receipt {
            get {
                return ResourceManager.GetString("Text_Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng.
        /// </summary>
        public static string Text_Total {
            get {
                return ResourceManager.GetString("Text_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ tối đa 255 kí tự.
        /// </summary>
        public static string Validate_MaxLength_Address {
            get {
                return ResourceManager.GetString("Validate_MaxLength_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên tối đa 36 kí tự.
        /// </summary>
        public static string Validate_MaxLength_EmployeeId {
            get {
                return ResourceManager.GetString("Validate_MaxLength_EmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhà cung cấp tối đa 36 kí tự.
        /// </summary>
        public static string Validate_MaxLength_ProviderId {
            get {
                return ResourceManager.GetString("Validate_MaxLength_ProviderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhà cung cấp tối đa 255 kí tự.
        /// </summary>
        public static string Validate_MaxLength_ProviderName {
            get {
                return ResourceManager.GetString("Validate_MaxLength_ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lí do chi tối đa 255 kí tự.
        /// </summary>
        public static string Validate_MaxLength_Reason {
            get {
                return ResourceManager.GetString("Validate_MaxLength_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số phiếu chi tối đa 20 kí tự.
        /// </summary>
        public static string Validate_MaxLength_ReceiptNumber {
            get {
                return ResourceManager.GetString("Validate_MaxLength_ReceiptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người nhận tối đa 100 kí tự.
        /// </summary>
        public static string Validate_MaxLength_ReceiveName {
            get {
                return ResourceManager.GetString("Validate_MaxLength_ReceiveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập chứng từ chi tiết.
        /// </summary>
        public static string Validate_NotNull_Accountant {
            get {
                return ResourceManager.GetString("Validate_NotNull_Accountant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản nợ không được để trống.
        /// </summary>
        public static string Validate_NotNull_AccountBalance {
            get {
                return ResourceManager.GetString("Validate_NotNull_AccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản có không được để trống.
        /// </summary>
        public static string Validate_NotNull_AccountDebt {
            get {
                return ResourceManager.GetString("Validate_NotNull_AccountDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hạch toán không được để trống.
        /// </summary>
        public static string Validate_NotNull_AccountingDate {
            get {
                return ResourceManager.GetString("Validate_NotNull_AccountingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày phiếu chi không được để trống.
        /// </summary>
        public static string Validate_NotNull_ReceiptDate {
            get {
                return ResourceManager.GetString("Validate_NotNull_ReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số phiếu chi không được để trống.
        /// </summary>
        public static string Validate_NotNull_ReceiptNumber {
            get {
                return ResourceManager.GetString("Validate_NotNull_ReceiptNumber", resourceCulture);
            }
        }
    }
}
