//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.WebFresher042023.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.WebFresher042023.Core.Resources.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tài nguyên.
        /// </summary>
        public static string Exception_NotFound_Default {
            get {
                return ResourceManager.GetString("Exception_NotFound_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi hệ thống.
        /// </summary>
        public static string Exception_System_default {
            get {
                return ResourceManager.GetString("Exception_System_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ, vui lòng kiểm tra lại.
        /// </summary>
        public static string Exception_Validate_Default {
            get {
                return ResourceManager.GetString("Exception_Validate_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh_sach_nhan_vien.xlsx.
        /// </summary>
        public static string Export_FileName {
            get {
                return ResourceManager.GetString("Export_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản.
        /// </summary>
        public static string Export_Title_ColumnBankAccount {
            get {
                return ResourceManager.GetString("Export_Title_ColumnBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh.
        /// </summary>
        public static string Export_Title_ColumnBankBranch {
            get {
                return ResourceManager.GetString("Export_Title_ColumnBankBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ngân hàng.
        /// </summary>
        public static string Export_Title_ColumnBankName {
            get {
                return ResourceManager.GetString("Export_Title_ColumnBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên.
        /// </summary>
        public static string Export_Title_ColumnCode {
            get {
                return ResourceManager.GetString("Export_Title_ColumnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đơn vị.
        /// </summary>
        public static string Export_Title_ColumnDepartment {
            get {
                return ResourceManager.GetString("Export_Title_ColumnDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string Export_Title_ColumnDOB {
            get {
                return ResourceManager.GetString("Export_Title_ColumnDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        public static string Export_Title_ColumnFulName {
            get {
                return ResourceManager.GetString("Export_Title_ColumnFulName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        public static string Export_Title_ColumnGender {
            get {
                return ResourceManager.GetString("Export_Title_ColumnGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMND.
        /// </summary>
        public static string Export_Title_ColumnIdentityNumber {
            get {
                return ResourceManager.GetString("Export_Title_ColumnIdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức danh.
        /// </summary>
        public static string Export_Title_ColumnPosition {
            get {
                return ResourceManager.GetString("Export_Title_ColumnPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string Export_Title_ColumnSTT {
            get {
                return ResourceManager.GetString("Export_Title_ColumnSTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANH SÁCH NHÂN VIÊN.
        /// </summary>
        public static string Export_Title_Employee {
            get {
                return ResourceManager.GetString("Export_Title_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        public static string Gender_Other {
            get {
                return ResourceManager.GetString("Gender_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\S+@\S+\.\S+$.
        /// </summary>
        public static string Regex_Email {
            get {
                return ResourceManager.GetString("Regex_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\d+$.
        /// </summary>
        public static string Regex_Number {
            get {
                return ResourceManager.GetString("Regex_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedDate.
        /// </summary>
        public static string Text_CreatedDate {
            get {
                return ResourceManager.GetString("Text_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DepartmentId.
        /// </summary>
        public static string Text_DepartmentId {
            get {
                return ResourceManager.GetString("Text_DepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateOfBirth.
        /// </summary>
        public static string Text_DOB {
            get {
                return ResourceManager.GetString("Text_DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Text_Email {
            get {
                return ResourceManager.GetString("Text_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeCode.
        /// </summary>
        public static string Text_EmployeeCode {
            get {
                return ResourceManager.GetString("Text_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName.
        /// </summary>
        public static string Text_FullName {
            get {
                return ResourceManager.GetString("Text_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityDate.
        /// </summary>
        public static string Text_IdentityDate {
            get {
                return ResourceManager.GetString("Text_IdentityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifiedDate.
        /// </summary>
        public static string Text_ModifiedDate {
            get {
                return ResourceManager.GetString("Text_ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng.
        /// </summary>
        public static string Validate_Email_ErrorFormat {
            get {
                return ResourceManager.GetString("Validate_Email_ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên phải kết thúc bằng số.
        /// </summary>
        public static string Validate_EndNum_Employee_Code {
            get {
                return ResourceManager.GetString("Validate_EndNum_Employee_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại trong hệ thống.
        /// </summary>
        public static string Validate_Exist_Employee_Code {
            get {
                return ResourceManager.GetString("Validate_Exist_Employee_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chứng minh không đúng.
        /// </summary>
        public static string Validate_IdentityNumber_Error {
            get {
                return ResourceManager.GetString("Validate_IdentityNumber_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo không được lớn hơn ngày hiện tại.
        /// </summary>
        public static string Validate_Invalid_CreatedDate {
            get {
                return ResourceManager.GetString("Validate_Invalid_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh không được lớn hơn ngày hiện tại.
        /// </summary>
        public static string Validate_Invalid_DOB {
            get {
                return ResourceManager.GetString("Validate_Invalid_DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp không được lớn hơn ngày hiện tại.
        /// </summary>
        public static string Validate_Invalid_IdentityDate {
            get {
                return ResourceManager.GetString("Validate_Invalid_IdentityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sửa không được lớn hơn ngày hiện tại.
        /// </summary>
        public static string Validate_Invalid_ModifiedDate {
            get {
                return ResourceManager.GetString("Validate_Invalid_ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ tối đa 255 kí tự.
        /// </summary>
        public static string Validate_MaxLength_Employee_Address {
            get {
                return ResourceManager.GetString("Validate_MaxLength_Employee_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản ngân hàng tối đa 50 kí tự.
        /// </summary>
        public static string Validate_MaxLength_Employee_BankAccount {
            get {
                return ResourceManager.GetString("Validate_MaxLength_Employee_BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh ngân hàng tối đa 255 kí tự.
        /// </summary>
        public static string Validate_MaxLength_Employee_BankBranch {
            get {
                return ResourceManager.GetString("Validate_MaxLength_Employee_BankBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ngân hàng tối đa 255 kí tự.
        /// </summary>
        public static string Validate_MaxLength_Employee_BankName {
            get {
                return ResourceManager.GetString("Validate_MaxLength_Employee_BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên tối đa 20 kí tự.
        /// </summary>
        public static string Validate_MaxLength_Employee_Code {
            get {
                return ResourceManager.GetString("Validate_MaxLength_Employee_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email tối đa 100 kí tự.
        /// </summary>
        public static string Validate_MaxLength_Employee_Email {
            get {
                return ResourceManager.GetString("Validate_MaxLength_Employee_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên tối đa 100 kí tự.
        /// </summary>
        public static string Validate_MaxLength_Employee_FullName {
            get {
                return ResourceManager.GetString("Validate_MaxLength_Employee_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chứng minh tối đa 25 kí tự.
        /// </summary>
        public static string Validate_MaxLength_Employee_IdentityNumber {
            get {
                return ResourceManager.GetString("Validate_MaxLength_Employee_IdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi cấp tối đa 255 kí tự.
        /// </summary>
        public static string Validate_MaxLength_Employee_IdentityPlace {
            get {
                return ResourceManager.GetString("Validate_MaxLength_Employee_IdentityPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại cố định tối đa 50 kí tự.
        /// </summary>
        public static string Validate_MaxLength_Employee_PhoneLandline {
            get {
                return ResourceManager.GetString("Validate_MaxLength_Employee_PhoneLandline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại di động tối đa 50 kí tự.
        /// </summary>
        public static string Validate_MaxLength_Employee_PhoneNumber {
            get {
                return ResourceManager.GetString("Validate_MaxLength_Employee_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức danh tối đa 255 kí tự.
        /// </summary>
        public static string Validate_MaxLength_Employee_PositionName {
            get {
                return ResourceManager.GetString("Validate_MaxLength_Employee_PositionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị không tồn tại trong hệ thống.
        /// </summary>
        public static string Validate_NotExist_Department_Id {
            get {
                return ResourceManager.GetString("Validate_NotExist_Department_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy nhân viên có mã:.
        /// </summary>
        public static string Validate_NotFound_Employee_Code {
            get {
                return ResourceManager.GetString("Validate_NotFound_Employee_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy nhân viên có id:.
        /// </summary>
        public static string Validate_NotFound_Employee_Id {
            get {
                return ResourceManager.GetString("Validate_NotFound_Employee_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id cần sửa không trùng khớp.
        /// </summary>
        public static string Validate_NotMatch {
            get {
                return ResourceManager.GetString("Validate_NotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được phép để trống.
        /// </summary>
        public static string Validate_NotNull_Employee_Code {
            get {
                return ResourceManager.GetString("Validate_NotNull_Employee_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị không được phép để trống.
        /// </summary>
        public static string Validate_NotNull_Employee_Department {
            get {
                return ResourceManager.GetString("Validate_NotNull_Employee_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên không được phép để trống.
        /// </summary>
        public static string Validate_NotNull_Employee_FullName {
            get {
                return ResourceManager.GetString("Validate_NotNull_Employee_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi nhập liệu từ người dùng.
        /// </summary>
        public static string Validate_User_Input_Error {
            get {
                return ResourceManager.GetString("Validate_User_Input_Error", resourceCulture);
            }
        }
    }
}
